CREATE TABLE anggota (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    foto VARCHAR(255) NOT NULL,
    alamat TEXT NOT NULL,
    email VARCHAR(255) NOT NULL,
    no_hp VARCHAR(15) NOT NULL,
    id_user INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE
);
